"""Distinct Phase 5 public-validator mutation cases used by the regression suite."""

from pathlib import Path


FULL_LOOP = Path(".looppilot/full-loop")
CROSS_LOOP = FULL_LOOP / "CROSS-LOOP-VALIDATION-TEMPLATE.md"
ACCEPTANCE = FULL_LOOP / "PROJECT-ACCEPTANCE-TEMPLATE.md"
READINESS = FULL_LOOP / "RELEASE-READINESS-TEMPLATE.md"
REPORT = FULL_LOOP / "FINAL-DELIVERY-REPORT-TEMPLATE.md"
REVIEW = FULL_LOOP / "REVIEW-REPORT-TEMPLATE.md"
PROTOCOL = Path("docs/project-closure-and-final-delivery.md")

MISSING_CASES = (
    ("missing_cross_loop_template", CROSS_LOOP),
    ("missing_project_acceptance_template", ACCEPTANCE),
    ("missing_release_readiness_template", READINESS),
    ("missing_final_delivery_report_template", REPORT),
    ("missing_phase_five_protocol", PROTOCOL),
    ("missing_phase_five_validator", Path("scripts/project_closure_validation.py")),
    ("missing_phase_five_case_matrix", Path("tests/project_closure_case_matrix.py")),
)

REJECTION_CASES = (
    ("cross_invalid_status", None, CROSS_LOOP, "- Validation Status: inactive", "- Validation Status: complete", "invalid Validation Status"),
    ("cross_missing_included_loops", None, CROSS_LOOP, "## Included Loops", "## Included Loops Omitted", "missing required heading '## Included Loops'"),
    ("cross_missing_dependencies", None, CROSS_LOOP, "## Cross-Loop Dependencies", "## Dependencies Omitted", "missing required heading '## Cross-Loop Dependencies'"),
    ("cross_missing_flows", None, CROSS_LOOP, "## End-to-End User Flows", "## User Flows Omitted", "missing required heading '## End-to-End User Flows'"),
    ("cross_missing_requirements", None, CROSS_LOOP, "## Requirement Coverage", "## Requirement Coverage Omitted", "missing required heading '## Requirement Coverage'"),
    ("cross_missing_data_migration", None, CROSS_LOOP, "## Data and Migration Compatibility", "## Data Compatibility Omitted", "missing required heading '## Data and Migration Compatibility'"),
    ("cross_missing_permission_security", None, CROSS_LOOP, "## Identity, Permission, and Security Compatibility", "## Permission Compatibility Omitted", "missing required heading '## Identity, Permission, and Security Compatibility'"),
    ("cross_missing_rollback", None, CROSS_LOOP, "## Rollback and Compensation Relationships", "## Rollback Omitted", "missing required heading '## Rollback and Compensation Relationships'"),
    ("cross_missing_validation_performed", None, CROSS_LOOP, "## Validation Performed", "## Validation Evidence Omitted", "missing required heading '## Validation Performed'"),
    ("cross_missing_skipped_validation", None, CROSS_LOOP, "## Skipped or Not-Applicable Validation", "## Skips Omitted", "missing required heading '## Skipped or Not-Applicable Validation'"),
    ("cross_missing_coverage_limitations", None, CROSS_LOOP, "## Coverage Limitations", "## Limitations Omitted", "missing required heading '## Coverage Limitations'"),
    ("cross_passed_with_failed_result", "cross", CROSS_LOOP, "| end-to-end scenario | pass | observed test output |", "| end-to-end scenario | failed | observed failure |", "passed cannot contain failed validation"),
    ("cross_passed_with_blocker", "cross", CROSS_LOOP, "## Project-Level Findings\n\n| Finding Reference | Severity | Target Remediation Loop | Status Source |\n|---|---|---|---|\n| None | none | none | none |", "## Project-Level Findings\n\n| Finding Reference | Severity | Target Remediation Loop | Status Source |\n|---|---|---|---|\n| FINDING-001 | blocker | LOOP-002 | loops/LOOP-002/FINDING-LEDGER.md |", "passed Validation cannot contain a Project Blocker"),
    ("cross_limitations_undisclosed", "cross-limitations", CROSS_LOOP, "- Remote production traffic was not exercised.", "- None.", "passed-with-limitations requires a disclosed limitation"),
    ("cross_closed_auto_pass", None, CROSS_LOOP, None, "\nAll mandatory Loops are closed; therefore Validation Status is passed.\n", "closed Loops must not automatically pass"),
    ("cross_claims_project_authority", None, CROSS_LOOP, None, "\nValidation owns Project status.\n", "Cross-Loop Validation must not own Project status"),
    ("cross_missing_project_authority_note", None, CROSS_LOOP, "`PROJECT.md` remains the only\nProject status authority", "`PROJECT.md` is merely a reference", "Cross-Loop Validation must not own Project status"),
    ("cross_inactive_real_loop", None, CROSS_LOOP, "| None | no | none | none | none | no |", "| LOOP-001 | no | closed | CLOSURE-001 | abc1234 | yes |", "inactive template contains a real Loop"),
    ("mapping_invalid_requirement_id", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQUIREMENT-1 | mandatory | goal | LOOP-001 | outcome | evidence | passed |", "invalid Requirement ID"),
    ("mapping_duplicate_requirement_id", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | mandatory | goal | LOOP-001 | outcome | evidence | passed |\n| REQ-001 | optional | goal two | LOOP-002 | outcome | evidence | passed |", "duplicate Requirement ID"),
    ("mapping_delivered_without_loop", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | optional | goal | none | outcome | evidence | passed |", "delivered Requirement requires a responsible Loop"),
    ("mapping_delivered_without_evidence", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | optional | goal | LOOP-001 | outcome | none | passed |", "delivered Requirement requires acceptance evidence"),
    ("mapping_cancelled_counted_passed", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | cancelled | old goal | LOOP-001 | outcome | evidence | passed |", "cancelled Requirement cannot be counted as passed"),
    ("mapping_excluded_counted_passed", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | excluded | excluded goal | LOOP-001 | outcome | evidence | passed |", "excluded Requirement cannot be counted as passed"),
    ("mapping_deferred_not_disclosed", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | deferred | later goal | LOOP-001 | future outcome | future evidence | deferred |", "deferred Requirement must be disclosed"),
    ("mapping_mandatory_missing_outcome", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | mandatory | goal | LOOP-001 | none | evidence | pending |", "mandatory Requirement missing mapping field 'Delivered Outcome'"),
    ("mapping_invalid_class", None, ACCEPTANCE, "| None | none | none | none | none | none | pending |", "| REQ-001 | urgent | goal | LOOP-001 | outcome | evidence | pending |", "invalid Requirement Class"),
    ("acceptance_invalid_status", None, ACCEPTANCE, "- Acceptance Status: inactive", "- Acceptance Status: completed", "invalid Acceptance Status"),
    ("acceptance_missing_original_goal", None, ACCEPTANCE, "## Original User Goal", "## Original Goal Omitted", "missing required heading '## Original User Goal'"),
    ("acceptance_missing_goal_mapping", None, ACCEPTANCE, "## Goal-to-Evidence Mapping", "## Goal Mapping Omitted", "missing required heading '## Goal-to-Evidence Mapping'"),
    ("acceptance_missing_loop_summary", None, ACCEPTANCE, "## Mandatory Loop Summary", "## Loop Summary Omitted", "missing required heading '## Mandatory Loop Summary'"),
    ("acceptance_missing_cross_validation", None, ACCEPTANCE, "## Cross-Loop Validation", "## Cross Validation Omitted", "missing required heading '## Cross-Loop Validation'"),
    ("acceptance_missing_spec_review", None, ACCEPTANCE, "### Project Spec Review", "### Spec Review Omitted", "missing required heading '### Project Spec Review'"),
    ("acceptance_missing_standards_review", None, ACCEPTANCE, "### Project Standards Review", "### Standards Review Omitted", "missing required heading '### Project Standards Review'"),
    ("acceptance_missing_functional", None, ACCEPTANCE, "## Project Functional Acceptance", "## Functional Acceptance Omitted", "missing required heading '## Project Functional Acceptance'"),
    ("acceptance_missing_engineering", None, ACCEPTANCE, "## Project Engineering Acceptance", "## Engineering Acceptance Omitted", "missing required heading '## Project Engineering Acceptance'"),
    ("acceptance_missing_delivery", None, ACCEPTANCE, "## Project Delivery Acceptance", "## Delivery Acceptance Omitted", "missing required heading '## Project Delivery Acceptance'"),
    ("acceptance_missing_recovery", None, ACCEPTANCE, "## Final Recovery State", "## Recovery State Omitted", "missing required heading '## Final Recovery State'"),
    ("acceptance_missing_report", None, ACCEPTANCE, "## Final Delivery Report", "## Delivery Report Omitted", "missing required heading '## Final Delivery Report'"),
    ("accepted_spec_failed", "acceptance", ACCEPTANCE, "### Project Spec Review\n\n- Result: pass", "### Project Spec Review\n\n- Result: fail", "accepted Project requires Project Spec Review pass"),
    ("accepted_standards_failed", "acceptance", ACCEPTANCE, "### Project Standards Review\n\n- Result: pass", "### Project Standards Review\n\n- Result: fail", "accepted Project requires Project Standards Review pass"),
    ("accepted_functional_failed", "acceptance", ACCEPTANCE, "## Project Functional Acceptance\n\n- Result: pass", "## Project Functional Acceptance\n\n- Result: fail", "accepted Project requires Functional Acceptance pass"),
    ("accepted_engineering_failed", "acceptance", ACCEPTANCE, "## Project Engineering Acceptance\n\n- Result: pass", "## Project Engineering Acceptance\n\n- Result: fail", "accepted Project requires Engineering Acceptance pass"),
    ("accepted_delivery_failed", "acceptance", ACCEPTANCE, "## Project Delivery Acceptance\n\n- Result: pass", "## Project Delivery Acceptance\n\n- Result: fail", "accepted Project requires Delivery Acceptance pass"),
    ("accepted_with_blocker", "acceptance", ACCEPTANCE, "| None | none | none | none | none | none |", "| FINDING-001 | blocker | LOOP-002 | loops/LOOP-002/FINDING-LEDGER.md | open | rework |", "Project Blocker prevents Project Acceptance"),
    ("accepted_risks_not_disclosed", "acceptance-risks", ACCEPTANCE, "- Minor documentation lag accepted by the Supervisor.", "- None.", "accepted-with-risks requires disclosed risks"),
    ("accepted_risk_without_authority", "acceptance-risks", ACCEPTANCE, "- Decision by: supervisor", "- Decision by: none", "accepted-with-risks requires authorized risk decision"),
    ("blocked_requests_closed", "acceptance-blocked", ACCEPTANCE, "- Requested Project status: none", "- Requested Project status: closed", "blocked Acceptance must not request Project closed"),
    ("acceptance_wrong_status_authority", None, ACCEPTANCE, "- Status authority: PROJECT.md", "- Status authority: PROJECT-ACCEPTANCE.md", "PROJECT.md must remain the Project status authority"),
    ("acceptance_claims_status_authority", None, ACCEPTANCE, None, "\nProject Acceptance owns Project status.\n", "Project Acceptance must not own Project status"),
    ("acceptance_infers_release", None, ACCEPTANCE, None, "\nProject accepted; therefore Release authorized: yes.\n", "must not infer release authorization"),
    ("accepted_missing_final_checkpoint", "acceptance", ACCEPTANCE, "- Final Checkpoint: CHECKPOINT-001", "- Closure Checkpoint: none", "missing required field 'Final Checkpoint'"),
    ("accepted_missing_final_report", "acceptance", ACCEPTANCE, "- Report: FINAL-REPORT-001", "- Delivery Report reference: none", "missing required field 'Report'"),
    ("accepted_release_required_unexecuted", "acceptance", ACCEPTANCE, "- Delivery mode: delivery-only", "- Delivery mode: release-required", "unsatisfied release obligation"),
    ("accepted_cross_validation_failed", "acceptance", ACCEPTANCE, "- Result: passed", "- Result: failed", "accepted Project requires Cross-Loop Validation pass"),
    ("accepted_mandatory_loop_not_closed", "acceptance", ACCEPTANCE, "| LOOP-001 | yes | LOOP-MAP.md | CLOSURE-001 | closed | observed closure |", "| LOOP-001 | yes | LOOP-MAP.md | CLOSURE-001 | in-progress | observed closure |", "accepted Project requires every mandatory Loop closed"),
    ("accepted_mandatory_loop_missing_evidence", "acceptance", ACCEPTANCE, "| LOOP-001 | yes | LOOP-MAP.md | CLOSURE-001 | closed | observed closure |", "| LOOP-001 | yes | LOOP-MAP.md | none | closed | none |", "mandatory Loop requires Closure and evidence"),
    ("review_invalid_level", None, REVIEW, "- Review Level: none", "- Review Level: program", "invalid Review Level"),
    ("active_review_missing_level", "loop-review", REVIEW, "- Review Level: loop", "- Review Level: none", "active Review requires Review Level"),
    ("project_review_missing_project_id", "review", REVIEW, "- Project ID: PROJECT-001", "- Project ID: none", "Project-level Review requires Project ID"),
    ("project_review_missing_cross_validation", "review", REVIEW, "- Reviewed Cross-Loop Validation: VALIDATION-001", "- Reviewed Cross-Loop Validation: none", "Project-level Review requires Cross-Loop Validation"),
    ("project_review_missing_goal_mapping", "review", REVIEW, "- Reviewed Goal Mapping: ACCEPTANCE-001", "- Reviewed Goal Mapping: none", "Project-level Review requires Goal-to-Evidence Mapping"),
    ("project_review_missing_boundary", "review", REVIEW, "- Reviewed Boundary: 0123456789abcdef", "- Reviewed Boundary: none", "Project-level Review requires reviewed boundary"),
    ("project_review_requires_no_loop", "review", REVIEW, "- Loop ID: not-applicable", "- Loop ID: LOOP-001", "Project-level Review Loop ID must be not-applicable"),
    ("specialist_replaces_axes", "review-specialist", REVIEW, None, "\nA specialist replaces both axes.\n", "Project specialist Review must not replace mandatory axes"),
    ("project_review_claims_status", "review", REVIEW, None, "\nProject-level Review owns Project status.\n", "Project Review must not own Project status"),
    ("loop_review_missing_loop_id", "loop-review", REVIEW, "- Loop ID: LOOP-001", "- Loop ID: none", "Loop-level Review requires a valid Loop ID"),
    ("readiness_invalid_status", None, READINESS, "- Readiness Status: inactive", "- Readiness Status: shippable", "invalid Readiness Status"),
    ("not_applicable_release_required", "readiness-na", READINESS, "- Delivery mode: delivery-only", "- Delivery mode: release-required", "not-applicable Release Readiness requires delivery-only mode"),
    ("ready_missing_rollback", "readiness", READINESS, "- Code rollback: restore the previous package", "- Code rollback: none", "ready Release Readiness requires rollback"),
    ("ready_missing_operations", "readiness", READINESS, "- Health checks: observed staging health check", "- Health checks: none", "ready Release Readiness requires operations evidence"),
    ("ready_missing_security", "readiness", READINESS, "- Security Review: pass", "- Security Review: none", "ready Release Readiness requires security review"),
    ("ready_risks_not_disclosed", "readiness-risks", READINESS, "- Minor changelog formatting risk accepted.", "- None.", "ready-with-accepted-risks requires disclosed risks"),
    ("ready_risk_without_authority", "readiness-risks", READINESS, "- Risk acceptance authority: supervisor decision", "- Risk acceptance authority: none", "ready-with-accepted-risks requires risk acceptance authority"),
    ("ready_with_readiness_gap", "readiness", READINESS, "## Readiness Gaps\n\n- None.", "## Readiness Gaps\n\n- Blocker: artifact signature missing.", "ready Release Readiness cannot contain readiness gaps"),
    ("release_without_authority", "readiness", READINESS, "- Release result: not-executed-not-authorized", "- Release result: released", "release execution requires independent authority"),
    ("tag_without_authority", "readiness", READINESS, "- Tag result: not-executed", "- Tag result: created", "tag execution requires independent authority"),
    ("deploy_without_authority", "readiness", READINESS, "- Deployment result: not-executed", "- Deployment result: deployed", "deployment execution requires independent authority"),
    ("migration_without_authority", "readiness", READINESS, "- Migration result: not-executed", "- Migration result: migrated", "migration execution requires independent authority"),
    ("traffic_without_authority", "readiness", READINESS, "- Traffic change result: not-executed", "- Traffic change result: changed", "traffic change execution requires independent authority"),
    ("rollback_without_authority", "readiness", READINESS, "- Rollback result: not-executed", "- Rollback result: rolled-back", "rollback execution requires independent authority"),
    ("push_implies_release", None, READINESS, None, "\nPush authorized: yes therefore Release authorized: yes.\n", "Push authority must not imply Release authority"),
    ("release_implies_deploy", None, READINESS, None, "\nRelease authorized: yes therefore Deploy authorized: yes.\n", "Release authority must not imply Deploy authority"),
    ("readiness_executes_release", None, READINESS, None, "\nReadiness executes the release.\n", "Readiness must not execute release"),
    ("readiness_owns_project_status", None, READINESS, None, "\nReadiness owns Project status.\n", "Release Readiness must not own Project status"),
    ("report_invalid_status", None, REPORT, "- Report Status: inactive", "- Report Status: delivered", "invalid Report Status"),
    ("report_missing_executive", None, REPORT, "## Executive Summary", "## Executive Summary Omitted", "missing required heading '## Executive Summary'"),
    ("report_missing_outcomes", None, REPORT, "## Delivered Outcomes", "## Outcomes Omitted", "missing required heading '## Delivered Outcomes'"),
    ("report_missing_verification", None, REPORT, "## Verification Summary", "## Verification Omitted", "missing required heading '## Verification Summary'"),
    ("report_missing_deferred", None, REPORT, "## Deferred Work", "## Deferred Work Omitted", "missing required heading '## Deferred Work'"),
    ("report_missing_accepted_risks", None, REPORT, "## Accepted Risks", "## Accepted Risks Omitted", "missing required heading '## Accepted Risks'"),
    ("report_missing_known_limitations", None, REPORT, "## Known Limitations", "## Limitations Omitted", "missing required heading '## Known Limitations'"),
    ("report_missing_exclusions", None, REPORT, "## Excluded and Cancelled Work", "## Exclusions Omitted", "missing required heading '## Excluded and Cancelled Work'"),
    ("report_missing_recovery", None, REPORT, "## Final Recovery Boundary", "## Recovery Boundary Omitted", "missing required heading '## Final Recovery Boundary'"),
    ("report_missing_unverified", None, REPORT, "## Unverified Items", "## Unverified Items Omitted", "missing required heading '## Unverified Items'"),
    ("ready_report_missing_acceptance", "report", REPORT, "- Acceptance: ACCEPTANCE-001", "- Acceptance: none", "ready Final Delivery Report requires Project Acceptance"),
    ("issued_report_missing_recipient", "report-issued", REPORT, "- Intended recipient: maintenance team", "- Intended recipient: none", "issued Final Delivery Report requires a real recipient"),
    ("report_claims_unauthorized_release", "report", REPORT, "- Release result: not-executed", "- Release result: released", "must not claim an unauthorized release"),
    ("report_claims_unauthorized_deploy", "report", REPORT, "- Deployment result: not-executed", "- Deployment result: deployed", "must not claim an unauthorized deployment"),
    ("report_owns_project_status", None, REPORT, None, "\nFinal Delivery Report owns Project status.\n", "Final Report must not own Project status"),
    ("report_copies_complete_ledger", None, REPORT, None, "\nInclude the complete Task Ledger in this report.\n", "Final Report must not copy a complete Ledger"),
    ("protocol_missing_project_authority", None, PROTOCOL, "- `PROJECT.md` is the only authority for Project status.", "- Project Acceptance is the Project status source.", "missing state-source invariant"),
    ("protocol_missing_loop_authority", None, PROTOCOL, "- `LOOP-MAP.md` is the only authority for Loop status.", "- Loop status may be copied.", "missing state-source invariant"),
    ("protocol_missing_task_authority", None, PROTOCOL, "- `TASK-LEDGER.md` is the only authority for Task status.", "- Task status may be copied.", "missing state-source invariant"),
    ("protocol_missing_finding_authority", None, PROTOCOL, "- `FINDING-LEDGER.md` is the only authority for Finding status.", "- Finding status may be copied.", "missing state-source invariant"),
    ("protocol_missing_recovery_authority", None, PROTOCOL, "- `CHECKPOINT.md` is the only Recovery authority.", "- Recovery may use any report.", "missing state-source invariant"),
    ("protocol_changes_loop_barriers", None, PROTOCOL, "the five Loop Barriers remain\nunchanged", "a sixth Loop Barrier is added", "must not alter the five Loop Barriers"),
    ("protocol_missing_terminal_reopen", None, PROTOCOL, "Resume item: PROJECT-CLOSED", "Resume item: CONTINUE-LATER", "missing terminal Final Checkpoint reopen condition"),
    ("protocol_parallel_finding_ledger", None, PROTOCOL, None, "\nProject Finding stores status in Project Finding Ledger.\n", "must not use a parallel Project Finding Ledger"),
    ("protocol_missing_static_boundary", None, PROTOCOL, "This protocol does not automate", "This protocol automatically performs", "protocol must disclose its static validation boundary"),
    ("protocol_missing_under_review_status", None, PROTOCOL, "`under-review`", "under review", "missing status declaration 'under-review'"),
)
